apiVersion: apps/v1
kind: Deployment
metadata:
  name: http-client
  labels:
    app: "http-client"
spec:
  selector:
    matchLabels:
      app: "http-client"
  replicas: 1
  template:
    metadata:
      labels:
        app: "http-client"
        tier: "appclient"
    spec:
      containers:
        - name: http-client
          image: djadvc/test-http-client
          resources:
            limits:
              cpu: 100m
              memory: 100Mi
          env:
            - name: WEBSITE_PORT
              value: "4443"
            - name: WEBSITE_HOST
              value: "web-server"
     