apiVersion: v1
kind: Service
metadata:
  name: web-server-service
  labels:
    app: web-server
spec:
  type: ClusterIP
  ports:
    - name: web-server
      port: 4443
      protocol: TCP
      targetPort: 4443
  selector:
    app: web-server